name: Build/Test CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [15]
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.32.10
    - name: Use Node.js ${{ matrix.node-version }}
      if: ${{ !env.ACT }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Build all packages
      run: pnpm build
    - name: Run unit tests
      run: pnpm turbo run test
